### ISSUE TITLE
Does it work under Nvidia or AMD Graphics cards

### ISSUE THREAD

**Issue by syshack** [01org/KVMGT-qemu#2]
does it work under Nvidia or AMD Graphics cards,like Grid k1/k2?

**Comment by jikesong** [comment]
No.

**Comment by syshack** [comment]
Thanks.BTW:whitch Graphics cards works? And is there any plan to support Nvidia and AMD ?

**Comment by jikesong** [comment]
Currently KVMGT works on Intel Haswell integrated graphics.

Although the GVT-g design is generic, however, adding support for a particular graphics means vendor-specific implementation, as least partially. So the answer to 2nd question is: there isn't such a plan so far.

**Comment by syshack** [comment]
Thanks,is any documents or step by step tutorial for it?

**Comment by jikesong** [comment]
not yet, hey - it's not a trivial work :)  

IMHO, the most important part, is to implement a GPU context switch method.  With that working piece, other components can be added to support  MPT time-sharing GPU.

**Comment by syshack** [comment]
Thank you, Song.In my case i wanna run AutoCAD in my vm,and followed the https://github.com/01org/KVMGT-qemu/blob/master/README.kvmgt ,but unfortunately,it doesn't work,the details https://github.com/01org/KVMGT-kernel/issues/10

**Comment by jikesong** [comment]
Let go #10 for further discussion.
